<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PersonaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('personas')->truncate();
        
        DB::table('personas')->insert([
                [
                    'id' => 1,
                    'area_id' => 1,
                    'nombre' => ' Mtra. Mónica Guillén Sánchez',
                    'cargo' => 'Secretaria',
                    'correo' => 'siresu@unach.mx',
                    'telefono' => '961 61 78000 Ext. 5551',
                    'foto' => 'directorio/01KWMS0PB91XE7XNJKS0V0GAHZ.png',
                    'orden' => 1,
                    'created_at' => '2026-02-15 22:38:53',
                    'updated_at' => '2026-07-03 19:59:13',
                ],
                [
                    'id' => 2,
                    'area_id' => 2,
                    'nombre' => 'Claudia Margarita Aquino López',
                    'cargo' => 'Directora de Proyectos y Programas',
                    'correo' => 'claudia.aquino@unach.mx',
                    'telefono' => '961 6178000 ext. 5556',
                    'foto' => 'directorio/01KWMSNBBXQAWS0501A7MM94N3.png',
                    'orden' => 1,
                    'created_at' => '2026-02-15 23:11:17',
                    'updated_at' => '2026-07-03 20:10:30',
                ],
                [
                    'id' => 3,
                    'area_id' => 2,
                    'nombre' => 'Mauricio Beltrán García',
                    'cargo' => 'Encargado del Departamento de Servicio Social',
                    'correo' => 'mauricio.beltran@unach.mx',
                    'telefono' => '9616178000 ext. 5556',
                    'foto' => 'directorio/01KWMSNBC5WDTSYADJ4H8FM81E.png',
                    'orden' => 3,
                    'created_at' => '2026-02-15 23:11:17',
                    'updated_at' => '2026-07-03 20:10:30',
                ],
                [
                    'id' => 4,
                    'area_id' => 2,
                    'nombre' => 'Lucila García López',
                    'cargo' => 'Encargada de Unidad y Vinculación Docente',
                    'correo' => 'luci.garcia@unach.mx',
                    'telefono' => '961 6178000 ext. 5556',
                    'foto' => 'directorio/01KWMSNBC34QZR91M2MWZQ4AGV.png',
                    'orden' => 2,
                    'created_at' => '2026-02-15 23:11:17',
                    'updated_at' => '2026-07-03 20:10:30',
                ],
                [
                    'id' => 5,
                    'area_id' => 2,
                    'nombre' => 'Jorge Coello Sesma',
                    'cargo' => 'Encargado del Departamento de Gestión Ambiental',
                    'correo' => 'jorge.sesma@unach.mx',
                    'telefono' => '6178000 ext. 5558',
                    'foto' => null,
                    'orden' => 4,
                    'created_at' => '2026-02-15 23:11:17',
                    'updated_at' => '2026-07-03 20:10:30',
                ],
                [
                    'id' => 6,
                    'area_id' => 3,
                    'nombre' => 'Ana Leybi Zuarth Tetumo',
                    'cargo' => 'Directora de Integración Universitaria',
                    'correo' => 'ana.zuarth@unach.mx',
                    'telefono' => '961 61 78000 Ext. 5553',
                    'foto' => 'directorio/01KWMVJNKW7W5NYHAHPS368YV4.png',
                    'orden' => 1,
                    'created_at' => '2026-02-15 23:14:33',
                    'updated_at' => '2026-07-03 20:44:00',
                ],
                [
                    'id' => 7,
                    'area_id' => 3,
                    'nombre' => 'Rossana Pineda Álvarez',
                    'cargo' => 'Encargada del departamento de Bienestar Estudiantil',
                    'correo' => 'cbe@unach.mx',
                    'telefono' => '961 61 78000 Ext. 5552, 5554',
                    'foto' => 'directorio/01KWMVJNM3J3431HEQDW100Y0G.png',
                    'orden' => 2,
                    'created_at' => '2026-02-15 23:14:33',
                    'updated_at' => '2026-07-03 20:44:00',
                ],
                [
                    'id' => 9,
                    'area_id' => 3,
                    'nombre' => 'Fernando Daniel Durán Ruíz',
                    'cargo' => 'Encargado del Departamento de Arte y Cultura',
                    'correo' => 'fernando.duran@unach.mx',
                    'telefono' => '961 61 78000 Ext. 5553',
                    'foto' => 'directorio/01KWMVJNM7F96X2CTFZ9J92D2M.png',
                    'orden' => 3,
                    'created_at' => '2026-02-15 23:14:33',
                    'updated_at' => '2026-07-03 20:44:00',
                ],
                [
                    'id' => 10,
                    'area_id' => 3,
                    'nombre' => 'Ernesto Treviño Martínez',
                    'cargo' => 'Encargado del Departamento de Deportes',
                    'correo' => 'ernesto.martinez@unach.mx',
                    'telefono' => '961 61 78000 Ext. 8721',
                    'foto' => 'directorio/01KWMVJNMD4093MP7FDPTP0T6G.png',
                    'orden' => 4,
                    'created_at' => '2026-02-15 23:14:33',
                    'updated_at' => '2026-07-03 20:44:00',
                ],
                [
                    'id' => 11,
                    'area_id' => 4,
                    'nombre' => 'Gabriel Velázquez Toledo',
                    'cargo' => 'Encargado de la Dirección Editorial',
                    'correo' => 'direccioneditorial@unach.mx',
                    'telefono' => '961 61 26911',
                    'foto' => 'directorio/01KWMVQC8S0WD9WD5FV2Y2E64F.png',
                    'orden' => 1,
                    'created_at' => '2026-02-15 23:16:56',
                    'updated_at' => '2026-07-03 20:46:34',
                ],
                [
                    'id' => 12,
                    'area_id' => 1,
                    'nombre' => 'Aben Amar Rabanales Gúzman',
                    'cargo' => 'Secretario Técnico',
                    'correo' => 'aben.rabanales@unach.mx',
                    'telefono' => '961 61 78000 Ext. 5559',
                    'foto' => 'directorio/01KWMS0PC0Z0VF6JNGPA0453F1.png',
                    'orden' => 2,
                    'created_at' => '2026-02-16 14:26:09',
                    'updated_at' => '2026-07-03 19:59:13',
                ],
                [
                    'id' => 13,
                    'area_id' => 1,
                    'nombre' => 'Carlos Javier Hernández Zebadúa',
                    'cargo' => 'Encargado de Apoyo Administrativo',
                    'correo' => 'carlos.hernandez@unach.mx',
                    'telefono' => '961 61 78000 Ext. 5557',
                    'foto' => 'directorio/01KWMS0PC3T4PWEQDW91MH8MPN.png',
                    'orden' => 3,
                    'created_at' => '2026-07-03 19:59:13',
                    'updated_at' => '2026-07-03 19:59:13',
                ],
                [
                    'id' => 14,
                    'area_id' => 1,
                    'nombre' => 'Rosa Isela Cruz González',
                    'cargo' => 'Coordinadora de Extensión  Istmo Costa y Soconusco',
                    'correo' => 'rosa.cruz@unach.mx',
                    'telefono' => null,
                    'foto' => 'directorio/01KWMS0PC7KYGPK8G4ZXP0ZYV5.png',
                    'orden' => 4,
                    'created_at' => '2026-07-03 19:59:13',
                    'updated_at' => '2026-07-03 19:59:13',
                ],
                [
                    'id' => 15,
                    'area_id' => 1,
                    'nombre' => 'Mariano Villatoro Bermúdez',
                    'cargo' => 'Coordinador de Extensión  Altos y Meseta Comiteca',
                    'correo' => 'marianov@unach.mx',
                    'telefono' => '961 67 88983',
                    'foto' => 'directorio/01KWMS0PCBQ0Y3G4RKSZG8HG3J.png',
                    'orden' => 5,
                    'created_at' => '2026-07-03 19:59:13',
                    'updated_at' => '2026-07-03 19:59:13',
                ],
                [
                    'id' => 16,
                    'area_id' => 2,
                    'nombre' => 'Roberto Cándido Cruz Nucamendi',
                    'cargo' => 'Responsabilidad Social Universitaria',
                    'correo' => 'siresu@unach.mx',
                    'telefono' => '961 61 78000 Ext. 5556',
                    'foto' => 'directorio/01KWMSNBCAME0ABFMMBH4MVBF2.png',
                    'orden' => 5,
                    'created_at' => '2026-07-03 20:10:30',
                    'updated_at' => '2026-07-03 20:10:30',
                ],
                [
                    'id' => 17,
                    'area_id' => 4,
                    'nombre' => 'Gustavo Adolfo González Escarela',
                    'cargo' => 'Encargado de Procesos Editoriales',
                    'correo' => 'gustavo.gonzalez@unach.mx',
                    'telefono' => '961 61 36701',
                    'foto' => 'directorio/01KWMVQC8Y14VK8XTGTW4QXWCC.png',
                    'orden' => 2,
                    'created_at' => '2026-07-03 20:46:34',
                    'updated_at' => '2026-07-03 20:46:34',
                ],
            ]);
        Schema::enableForeignKeyConstraints();
    }
}