name: CI/CD Pipeline SIRESU

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.12'
        extensions: mbstring, dom, curl, libxml, mysql, sqlite, pdo_sqlite

    - name: Copiar Entorno de Pruebas
      run: cp .env.example .env

    - name: Instalar Dependencias de Composer
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generar Encryption Key
      run: php artisan key:generate

    - name: Ejecutar Pruebas Automatizadas
      run: php artisan test

  deploy:
    runs-on: self-hosted
    needs: laravel-tests

    steps:
    - name: Desplegar en el Servidor de la UNACH vía SSH Nativo
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > temp_key
        chmod 600 temp_key
        ssh -o StrictHostKeyChecking=no -i temp_key -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/siresu/htdocs_nuevo/siresu-unach-web && chmod +x deploy.sh && ./deploy.sh"
        rm temp_key