name: Laravel SIRESU CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  # 1. TRABAJO DE PRUEBAS (CI)
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Cambia a la versión de PHP que manejes
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
        coverage: none

    - name: Copiar .env de pruebas
      run: cp .env.example .env

    - name: Instalar Dependencias de Composer
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generar Llave de Aplicación
      run: php artisan key:generate

    - name: Directorios de Permisos
      run: chmod -R 777 storage bootstrap/cache

    - name: Ejecutar Pruebas
      run: php artisan test

  # 2. TRABAJO DE DESPLIEGUE (CD)
  deploy:
    runs-on: self-hosted
    needs: laravel-tests

    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js y compilar Assets
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Compilar Frontend (Vite)
      run: |
        npm install
        npm run build

    - name: Ejecutar Script de Despliegue Local
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        cd ${{ github.workspace }}
        chmod +x deploy.sh
        ./deploy.sh